version: '3.8'
services:
  app:
    build:
      context: .
      args:
        uid: ${UID:-10000}
    image: tiagodevweb/php-apache
    container_name: app
    ports:
      - ${APP_PORT:-80}:80
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    volumes:
      - .:/var/www/html